import { AutoFormThemeBootstrap3 } from './autoform-bootstrap3'

AutoFormThemeBootstrap3.load = function () {
  // bootstrap3 Template - General
  require('./templates/bootstrap3/bootstrap3.js')
  // bootstrap3 Template - Components
  require('./templates/bootstrap3/components/quickForm/quickForm.html')
  require('./templates/bootstrap3/components/quickForm/quickForm.js')
  require('./templates/bootstrap3/components/afArrayField/afArrayField.html')
  require('./templates/bootstrap3/components/afArrayField/afArrayField.js')
  require('./templates/bootstrap3/components/afArrayField/afArrayField.css')
  require('./templates/bootstrap3/components/afFormGroup/afFormGroup.html')
  require('./templates/bootstrap3/components/afFormGroup/afFormGroup.js')
  require('./templates/bootstrap3/components/afObjectField/afObjectField.html')
  require('./templates/bootstrap3/components/afObjectField/afObjectField.js')
  // bootstrap3 Template - Input Types
  require('./templates/bootstrap3/inputTypes/boolean-checkbox/boolean-checkbox.html')
  require('./templates/bootstrap3/inputTypes/boolean-radios/boolean-radios.html')
  require('./templates/bootstrap3/inputTypes/boolean-radios/boolean-radios.js')
  require('./templates/bootstrap3/inputTypes/boolean-select/boolean-select.html')
  require('./templates/bootstrap3/inputTypes/button/button.html')
  require('./templates/bootstrap3/inputTypes/color/color.html')
  require('./templates/bootstrap3/inputTypes/date/date.html')
  require('./templates/bootstrap3/inputTypes/datetime/datetime.html')
  require('./templates/bootstrap3/inputTypes/datetime-local/datetime-local.html')
  require('./templates/bootstrap3/inputTypes/email/email.html')
  require('./templates/bootstrap3/inputTypes/month/month.html')
  require('./templates/bootstrap3/inputTypes/number/number.html')
  require('./templates/bootstrap3/inputTypes/password/password.html')
  require('./templates/bootstrap3/inputTypes/radio/radio.html')
  require('./templates/bootstrap3/inputTypes/radio/radio.js')
  require('./templates/bootstrap3/inputTypes/range/range.html')
  require('./templates/bootstrap3/inputTypes/reset/reset.html')
  require('./templates/bootstrap3/inputTypes/search/search.html')
  require('./templates/bootstrap3/inputTypes/select/select.html')
  require('./templates/bootstrap3/inputTypes/select-checkbox/select-checkbox.html')
  require('./templates/bootstrap3/inputTypes/select-checkbox/select-checkbox.js')
  require('./templates/bootstrap3/inputTypes/select-checkbox-inline/select-checkbox-inline.html')
  require('./templates/bootstrap3/inputTypes/select-checkbox-inline/select-checkbox-inline.js')
  require('./templates/bootstrap3/inputTypes/select-checkbox-inline/select-checkbox-inline.css')
  require('./templates/bootstrap3/inputTypes/select-multiple/select-multiple.html')
  require('./templates/bootstrap3/inputTypes/select-radio/select-radio.html')
  require('./templates/bootstrap3/inputTypes/select-radio/select-radio.js')
  require('./templates/bootstrap3/inputTypes/select-radio-inline/select-radio-inline.html')
  require('./templates/bootstrap3/inputTypes/select-radio-inline/select-radio-inline.js')
  require('./templates/bootstrap3/inputTypes/select-radio-inline/select-radio-inline.css')
  require('./templates/bootstrap3/inputTypes/submit/submit.html')
  require('./templates/bootstrap3/inputTypes/tel/tel.html')
  require('./templates/bootstrap3/inputTypes/text/text.html')
  require('./templates/bootstrap3/inputTypes/textarea/textarea.html')
  require('./templates/bootstrap3/inputTypes/time/time.html')
  require('./templates/bootstrap3/inputTypes/url/url.html')
  require('./templates/bootstrap3/inputTypes/week/week.html')
  // bootstrap3-horizontal Template - General
  require('./templates/bootstrap3-horizontal/bootstrap3-horizontal.css')
  // bootstrap3-horizontal Template - Components
  require('./templates/bootstrap3-horizontal/components/quickForm/quickForm.html')
  require('./templates/bootstrap3-horizontal/components/quickForm/quickForm.js')
  require('./templates/bootstrap3-horizontal/components/afArrayField/afArrayField.html')
  require('./templates/bootstrap3-horizontal/components/afArrayField/afArrayField.js')
  require('./templates/bootstrap3-horizontal/components/afFormGroup/afFormGroup.html')
  require('./templates/bootstrap3-horizontal/components/afFormGroup/afFormGroup.js')
  require('./templates/bootstrap3-horizontal/components/afObjectField/afObjectField.html')
  require('./templates/bootstrap3-horizontal/components/afObjectField/afObjectField.js')
  // bootstrap3-horizontal Template - Input Types
  require('./templates/bootstrap3-horizontal/inputTypes/boolean-checkbox/boolean-checkbox.html')
  require('./templates/bootstrap3-horizontal/inputTypes/boolean-checkbox/boolean-checkbox.js')
  // bootstrap3-inline Template
  require('./templates/bootstrap3-inline/bootstrap3-inline.html')
  require('./templates/bootstrap3-inline/bootstrap3-inline.js')
  require('./templates/bootstrap3-inline/bootstrap3-inline.css')
}

export { AutoFormThemeBootstrap3 }
